### ISSUE TITLE
Jenkins 2.0 support

### ISSUE THREAD

**Issue by jaybrueder** [chef-cookbooks/jenkins#466]
Hi!

I played around with the Jenkins 2.0 RC today. I was also curious to see if I can use it with the jenkins-cookbook. As it turns out, using the WAR install_method, I can install it without any problems:

```
node.default['jenkins']['master']['install_method'] = 'war'
node.default['jenkins']['master']['source'] = 'http://mirrors.jenkins-ci.org/war-rc/2.0/jenkins.war'
node.default['jenkins']['master']['checksum'] = 'd92d087856f9f085731579c5847851266d470b2b12f68aa2feeb8e60c6bf5091'
```

I can then use Jenkins 2.0 RC in the browser as intended.

However, using resources like `jenkins_plugin` won't work yet. Even with unlocking Jenkins, and using User credentials within the cookbook, I still get error messages:

```
================================================================================
           Error executing action `install` on resource 'jenkins_plugin[build-monitor-plugin]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '255'
           ---- Begin output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 install-plugin /tmp/kitchen/cache/build-monitor-plugin-1.6\+build.138.plugin -name build-monitor-plugin  ----
           STDOUT:
           STDERR: Apr 12, 2016 9:57:11 AM hudson.remoting.SynchronousCommandTransport$ReaderThread run
           SEVERE: I/O error in channel Chunked connection to http://localhost:8080/cli
           java.io.IOException: Premature EOF
            at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
            at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
            at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
            at java.io.FilterInputStream.read(FilterInputStream.java:133)
            at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3067)
            at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:90)
            at hudson.remoting.ChunkedInputStream.read(ChunkedInputStream.java:46)
            at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:97)
            at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
            at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
            at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)

           hudson.remoting.RequestAbortedException: java.io.IOException: Premature EOF
            at hudson.remoting.Request.abort(Request.java:303)
            at hudson.remoting.Channel.terminate(Channel.java:847)
            at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:69)
            at ......remote call to Chunked connection to http://localhost:8080/cli(Native Method)
            at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
            at hudson.remoting.Request.call(Request.java:172)
            at hudson.remoting.Channel.call(Channel.java:780)
            at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:250)
            at hudson.remoting.$Proxy1.waitForProperty(Unknown Source)
            at hudson.remoting.Channel.waitForRemoteProperty(Channel.java:1258)
            at hudson.cli.CLI.<init>(CLI.java:147)
            at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
            at hudson.cli.CLI._main(CLI.java:479)
            at hudson.cli.CLI.main(CLI.java:390)
           Caused by: java.io.IOException: Premature EOF
            at sun.net.www.http.ChunkedInputStream.readAheadBlocking(ChunkedInputStream.java:565)
            at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:609)
            at sun.net.www.http.ChunkedInputStream.read(ChunkedInputStream.java:696)
            at java.io.FilterInputStream.read(FilterInputStream.java:133)
            at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.read(HttpURLConnection.java:3067)
            at hudson.remoting.FlightRecorderInputStream.read(FlightRecorderInputStream.java:90)
            at hudson.remoting.ChunkedInputStream.read(ChunkedInputStream.java:46)
            at hudson.remoting.ChunkedInputStream.readUntilBreak(ChunkedInputStream.java:97)
            at hudson.remoting.ChunkedCommandTransport.readBlock(ChunkedCommandTransport.java:39)
            at hudson.remoting.AbstractSynchronousByteArrayCommandTransport.read(AbstractSynchronousByteArrayCommandTransport.java:34)
            at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:48)
           ---- End output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 install-plugin /tmp/kitchen/cache/build-monitor-plugin-1.6\+build.138.plugin -name build-monitor-plugin  ----
           Ran "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 install-plugin /tmp/kitchen/cache/build-monitor-plugin-1.6\+build.138.plugin -name build-monitor-plugin  returned 255
```

I take it this is because of the new SetupWizard / Default user authentication.

I also found some references of this in other tickets around the web:

https://issues.jenkins-ci.org/browse/JENKINS-34035
https://github.com/jenkinsci/jenkins/pull/2223

What are your plans on adding Jenkins 2.0 support to this cookbook in the future?

**Comment by ehaselwanter** [comment]
@schisamo @tas50 any comments? :-)

**Comment by schisamo** [comment]
We don't have any immediate plans.

**Comment by daften** [comment]
jenkins 2 is the default version on centos by now, does this change plans?

**Comment by daften** [comment]
I'm gonna try to fix the main issues the coming week and open a PR. Everybody that wants to help, let me know, i can give access to my fork to collaborate.

**Comment by AbraxasJung** [comment]
node.default['jenkins']['master']['jvm_options'] = '-Djenkins.install.runSetupWizard=false'

**Comment by daften** [comment]
As can be seen in my PR :P

**Comment by damphyr** [comment]
Anyone still working on this? I have a wrapper cookbook installing Jenkins 2.x using the jenkins-cookbook that works around several problems.

Turning off the wizard is not  the worst :)  The by default activated authentication is what breaks every jenkins-cli call (and this affects jenkins_user, jenkins_plugin etc.)

My current workaround is to turn off authentication by manipulating config.xml directly, do all the jenkins-cli work and then turn it back on again.

It would be more effective to read secrets/initialAdminPassword and use ```jenkins-cli login --username admin --password <bla>``` and maintain the session in the cookbook.

**Comment by oleg-nenashev** [comment]
> It would be more effective to read secrets/initialAdminPassword and use jenkins-cli login --username admin --password <bla> and maintain the session in the cookbook.

Yes, this is the right way for all installation wrappers

**Comment by daften** [comment]
@damphyr  The default auth is enabled BY the wizard ;) And the wizard is not needed when you actually set-up jenkins through CLI, You can easily enable auth yourself and install users by using a groovy script in your own wrapper cookbook. This cookbook should be here to install jenkins so a wrapper cookbook can install plugins, enable auth, ... which now needs some initial code. So jenkins 2 without a PR like this is almost unusable without some extra code to disable some stuff :)

And no, it would not be more effective, since the initialAdminPassword is only set after jenkins has started, which would make runs longer.

The other approach that could be done, is being able to set some attribute so you can at least add a key to the admin user that is automatically created, so CLI is usable out of the box at least. Feel free to make a PR that would do this ;)

**Comment by oleg-nenashev** [comment]
@daften @damphyr 
> You can easily enable auth yourself and install users by using a groovy script in your own wrapper cookbook. 

Yes, it should work. Groovy Boot Hook scripts are being executed before the installation wizard. Please keep in mind that you'll have to trigger the Authorization Strategy plugin installation in such case, because Jenkins 2 starts up without plugins. If you want to use the installation wizard UI, you may also get into [JENKINS-34881](https://issues.jenkins-ci.org/browse/JENKINS-34881), which has been fixed in Jenkins 2.9

CLI update seems to be much more convenient, but yeah it requires some magic

**Comment by damphyr** [comment]
@daften yeah, but if we disable the wizard (either by jvm parameter or by writing InstallUtil.lastExecVersion ) then there is no config.xml - and JNLP is not enabled because security is disabled!

So at the moment (and until the chicken and egg problem with the CLI in the Chef cookbook is resolved) I install with wizards activated, disable security, do my stuff (plugins, users, seed job), disable wizards and then re-enable security.

**Comment by daften** [comment]
The config.xml is only there after jenkins boots the first time. So wizard or not, you need jenkins to boot...

The wizard is there because many people install jenkins and don't enable security, or are lost in the interface. The wizard is NOT there for people installing jenkins through any provisioning tool, since those people will (or should) configure jenkins through chef (or puppet, or ansible, ...).

And I don't know what JNLP has to do with this. As far as I know, nothing in jenkins is disabled when security is disabled, and like I said, turning security on is very easy.

@damphyr  And what you're doing, are you doing this in the UI? Disable security and so forth. Because if so, you should really look into doing all of that with a groovy script. We have made some that could help you enable security through chef very easily. Also plugin install is done that way.

@oleg-nenashev It doesn't require magic if you do it properly :D You start with a fresh OS. Install jenkins and make sure it has no security, you install the first user through CLI then and give it a key-pair (from a secure data bag preferably), and enable security. No magic involved, no wand needed :)

I'm not saying your point of view is invalid, but I don't see them as use cases meant for people using chef. What I'd suggest is you create a PR that supports what you want, so the authors of the cookbook can compare. ;)

**Comment by damphyr** [comment]
@daften that is not the case, at least up until 2.8: Jenkins boots properly is there and you can do anything but the config.xml is not on disk (or not where I would expect it). Easy to test when starting Jenkins with -Djenkins.install.runSetupWizard=false

I found this out because I naively had a condition to wait on the appearance of config.xml for my recipe.

And no, I am not doing anything in the UI:

```
chef_gem 'nokogiri' do
  compile_time false
end

include_recipe 'jenkins::java'
include_recipe 'git::default'
include_recipe 'jenkins::master'

#Anything you want to do, do it after Jenkins shows up
#
#This way we make sure that Jenkins has created all files in it's home
include_recipe 'jenkins-master::wait_for_jenkins'
include_recipe 'jenkins-master::disable_security'
include_recipe 'jenkins-master::disable_wizards'
include_recipe 'jenkins-master::enable_jnlp'
include_recipe'jenkins-master::plugins'
```
jenkins-master::wait_for_jenkins actually still waits for config.xml to show up :)

**Comment by damphyr** [comment]
I also checkd to see what happens when Jenkins is restarted etc.  Still no config.xml (which perplexed me to no end). But I had to get something working and fast so I didn't put too much time into it.

**Comment by daften** [comment]
@damphyr Then maybe the behaviour changed. But I'm 100% sure if jenkins is booted, config.xml showed up when 2.x was just released. See this commit: https://github.com/chef-cookbooks/jenkins/pull/471/commits/22c3ea3acd8d7205a8c8be51515747d5befbe63b  for reference.

Without the config.xml, jenkins can't even boot. At boot jenkins checks if config.xml is there, and if it isn't, a default file is written. After that, when the wizard is enabled, the wizard will adapt jenkins' config.xml.

**Comment by daften** [comment]
Just confirmed that config.xml shows up after restart ;)

**Comment by etki** [comment]
@AbraxasJung you, sir, are my savior

**Comment by johnr-spindance** [comment]
👍 

Our Jenkins server is on 2.7.1 and we can no longer cook it, even with version 2.6.0 of this cookbook. Do you need any help with development on this branch to help push things along?

**Comment by StephenKing** [comment]
Do you have any further information? Jenkins 2 works fine wit setting the `jvm_options`(see my setup [here](https://github.com/TYPO3-cookbooks/site-chefcitypo3org/blob/develop/attributes/default.rb#L2))

**Comment by pedrorjbr** [comment]
Hello guys! Does anyone can provide me a guide how to install jenkins ? I am facing the same error. I could not even install a plugin. :(

I tryied:

```
node.default['jenkins']['master']['jvm_options'] = '-Djenkins.install.runSetupWizard=false'
include_recipe "jenkins::java"
include_recipe "jenkins::master"

jenkins_plugin 'matrix-auth'
jenkins_plugin 'credentials'
 
jenkins_script 'add_authentication' do
  command <<-EOH.gsub(/^ {4}/, '')

  import jenkins.model.*
  import hudson.security.*
  
  def instance = Jenkins.getInstance()
  
  def hudsonRealm = new HudsonPrivateSecurityRealm(false)
  hudsonRealm.createAccount("xxxx","yyyy")
  instance.setSecurityRealm(hudsonRealm)
  def strategy = new hudson.security.FullControlOnceLoggedInAuthorizationStrategy()
  strategy.setAllowAnonymousRead(false)
  instance.setAuthorizationStrategy(strategy)
    
  instance.save()
  
  EOH
end
```

**Comment by pedrorjbr** [comment]
@damphyr Could you provide your cookbook wrapper?

**Comment by daften** [comment]
Jenkins installs, but the starting fails with me locally too. Let me try to fix this this weekend. If somebody else is quicker, i'm gonna be really happy ;)

**Comment by daften** [comment]
I get jenkins to start based on the log now, the probleem seems to have been the java version (on centos). When I install the latest java, it starts fine it seems. I can't get the interface to load however.

**Comment by daften** [comment]
It was the java version, it started fine, i just forgot to disable iptables :s  It seems the java requirements should be higher now.
I've updated the PR and am running the kitchen tests. Any feedback is welcome off course.

**Comment by davidcpell** [comment]
This seems to be the most relevant/recent discussion I could find for my issue. I'm trying to set up a user per the cookbook instructions under `CLI > jenkins_user` and `Caveats > Authentication`. The relevant section of my recipe looks like this:

```
...
jenkins_keys = search(:keys, "id:jenkins").first
private_key  = jenkins_keys['private']
public_key   = jenkins_keys['public']

include_recipe 'jenkins::master'

node.default['jenkins_plugins'].each do |plugin|
  jenkins_plugin plugin
end

jenkins_user 'me' do
  full_name   'me me'
  public_keys [public_key]
end

node.run_state[:jenkins_private_key] = private_key
```

I tried to generally follow the order of things from the readme but have tried several orders and still no luck. This is the error I keep getting:

```
  ================================================================================
           Error executing action `create` on resource 'jenkins_user[rean]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           Expected process to exit with [0], but received '255'
           ---- Begin output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -i "/tmp/kitchen/cache/jenkins-key" groovy /tmp/groovy20160809-14509-1in0d02 ----
           STDOUT:
           STDERR: java.io.IOException: No X-Jenkins-CLI2-Port among [X-Jenkins, X-Required-Permission, null, X-You-Are-In-Group, Date, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Jenkins-Ses
sion, Set-Cookie, Content-Type, Server, X-Content-Type-Options]
                at hudson.cli.CLI.getCliTcpPort(CLI.java:284)
                at hudson.cli.CLI.<init>(CLI.java:128)
                at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
                at hudson.cli.CLI._main(CLI.java:473)
                at hudson.cli.CLI.main(CLI.java:384)
                Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli
                        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
                        at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)
                        at hudson.cli.CLI.connectViaHttp(CLI.java:152)
                        at hudson.cli.CLI.<init>(CLI.java:132)
                        ... 3 more
           ---- End output of "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -i "/tmp/kitchen/cache/jenkins-key" groovy /tmp/groovy20160809-14509-1in0d02 ----
           Ran "java" -jar "/tmp/kitchen/cache/jenkins-cli.jar" -s http://localhost:8080 -i "/tmp/kitchen/cache/jenkins-key" groovy /tmp/groovy20160809-14509-1in0d02 returned 255
```

Any idea what I'm doing wrong???

Using: Ubuntu 14.04 and Centos 7.2 through Test Kitchen + Vagrant

**Comment by scottzilla** [comment]
@davidcpell I think this is due to a missing Mailer plugin; I was able to solve this by installing the required plugins as noted in @daften's PR: https://github.com/chef-cookbooks/jenkins/pull/471/files

Specifically: 
`# Install some plugins needed, but not installed on jenkins2 by default
jenkins_plugins = %w(
  mailer
  credentials
  ssh-credentials
  ssh-slaves
)

jenkins_plugins.each do |plugin|
  jenkins_plugin plugin do
    notifies :execute, 'jenkins_command[safe-restart]', :immediately
  end
end

jenkins_command 'safe-restart' do
  action :nothing
end
`

My initial cookbook order is essentially:
- chef-sugar
- openjdk
- jenkins::master
- required plugins (noted above)
- auth
- ...
- etc.

**Comment by cheeseplus** [comment]
#557 has been merged (which includes most of #471)
