### ISSUE TITLE
user_resource_abstract_base_class[jenkins] fails with NotImplementedError

### ISSUE THREAD

**Issue by jmaass** [chef-cookbooks/jenkins#513]
### Cookbook version
2.6.0

### Chef-client version
12.14.89

### Platform Details
CentOS 7.0, 3.10.0-327.28.3.el7.x86_64

### Scenario:
Trying to install a jenkins-slave with the jenkins_private_key attribute set.

### Steps to Reproduce:
```
#
# Cookbook Name:: mnet_jenkins
# Recipe:: slave
#
# Copyright (C) 2016 M-net Telekommunikations GmbH
#
# All rights reserved - Do Not Redistribute
#
include_recipe 'role_default'
include_recipe 'chef-vault'

#
# Remove OpenJDK since it is standard on CentOS and we use Oracle
#
package ['java-1.8.0-openjdk', 'java-1.8.0-openjdk-headless' ] do
  action :purge
end

#
# Install the right Java
#
include_recipe 'java'

#
# Define some variables we need
#
master = node['jenkins']['master']['host']
ipaddress = node['ipaddress']
auth_user = node['mnet_jenkins']['auth_user']
jenkins_keys = chef_vault_item('mnet_jenkins', 'keys')

#
# Create the Jenkins OS group
#
group 'jenkins' do
  append  true
  gid     '11119'
  action  :create
end

#
# Create the jenkins OS User
#
user 'jenkins' do
  comment     'Jenkins Slave'
  home        '/home/jenkins'
  shell       '/bin/false'
  uid         '11119'
  group       'jenkins'
  action      :create
end

#
# Set the authentication key if we have an authentication user
#
ruby_block 'set_jenkins_private_key' do
  block do
    require 'openssl'
    require 'net/ssh'

    key = OpenSSL::PKey::RSA.new(jenkins_keys[auth_user]['private_key'])
    node.run_state[:jenkins_private_key] = key.to_pem
  end
  action :run
  not_if { auth_user == ''}
end

#
# Set up the slave
#
jenkins_jnlp_slave ipaddress do
  remote_fs '/home/jenkins'
  action [:create, :connect]
  not_if { master == 'localhost' }
end

```
### Expected Result:
The jenkins_jnlp_slave is set up and the converge succeeds.

### Actual Result:
```
       Recipe: mnet_jenkins::slave
         * group[jenkins] action create (up to date)
         * linux_user[jenkins] action create (up to date)
         * ruby_block[set_jenkins_private_key] action run
           - execute the ruby block set_jenkins_private_key
         * jenkins_jnlp_slave[192.168.211.147] action create
         Recipe: <Dynamically Defined Resource>
           * remote_file[/tmp/kitchen/cache/jenkins-cli.jar] action create (up to date)
           * remote_file[/tmp/kitchen/cache/update-center.json] action create (up to date)
           * file[/tmp/kitchen/cache/extracted-update-center.json] action create (up to date)
           * file[/tmp/kitchen/cache/jenkins-key] action create (up to date)
           * directory[/home/jenkins] action create (up to date)
           * group[jenkins] action create (up to date)
           * user_resource_abstract_base_class[jenkins] action create[2016-09-27T13:51:49+02:00] WARN: Class Chef::Provider::User does not declare 'provides :user'.
       [2016-09-27T13:51:49+02:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.
       
             
             ================================================================================
             Error executing action `create` on resource 'user_resource_abstract_base_class[jenkins]'
             ================================================================================
             
             NotImplementedError
             -------------------
             NotImplementedError
             
             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:60:in `action_create'
             
             Compiled Resource:
             ------------------
             # Declared in 
             
             user_resource_abstract_base_class("jenkins") do
        action [:create]
        supports {:manage_home=>false, :non_unique=>false}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        username "jenkins"
        comment "Jenkins slave user - Created by Chef"
        gid 11119
        home "/home/jenkins"
        iterations 27855
             end
             
             Platform:
             ---------
             x86_64-linux
             
           
           ================================================================================
           Error executing action `create` on resource 'jenkins_jnlp_slave[192.168.211.147]'
           ================================================================================
           
           NotImplementedError
           -------------------
           user_resource_abstract_base_class[jenkins] (dynamically defined) had an error: NotImplementedError: NotImplementedError
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:60:in `action_create'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb
           
            75: jenkins_jnlp_slave ipaddress do
            76:   remote_fs '/home/jenkins'
            77:   action [:create, :connect]
            78:   not_if { master == 'localhost' }
            79: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb:75:in `from_file'
           
           jenkins_jnlp_slave("192.168.211.147") do
             action [:create, :connect]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_jnlp_slave
             cookbook_name "mnet_jenkins"
             recipe_name "slave"
             remote_fs "/home/jenkins"
             slave_name "192.168.211.147"
             description "Jenkins slave 192.168.211.147"
             usage_mode "normal"
             group "jenkins"
             user "jenkins"
             not_if { #code block }
           end
           
           Platform:
           ---------
           x86_64-linux
           
       
       Running handlers:
       [2016-09-27T13:51:49+02:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-09-27T13:51:49+02:00] ERROR: Exception handlers complete
       Chef Client failed. 7 resources updated in 12 seconds
       [2016-09-27T13:51:49+02:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-09-27T13:51:49+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-09-27T13:51:49+02:00] ERROR: jenkins_jnlp_slave[192.168.211.147] (mnet_jenkins::slave line 75) had an error: NotImplementedError: user_resource_abstract_base_class[jenkins] (dynamically defined) had an error: NotImplementedError: NotImplementedError
       [2016-09-27T13:51:49+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <jenkins-slave-centos07>.  Please see .kitchen/logs/jenkins-slave-centos07.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
       Recipe: mnet_jenkins::slave
         * group[jenkins] action create (up to date)
         * linux_user[jenkins] action create (up to date)
         * ruby_block[set_jenkins_private_key] action run
           - execute the ruby block set_jenkins_private_key
         * jenkins_jnlp_slave[192.168.211.147] action create
         Recipe: <Dynamically Defined Resource>
           * remote_file[/tmp/kitchen/cache/jenkins-cli.jar] action create (up to date)
           * remote_file[/tmp/kitchen/cache/update-center.json] action create (up to date)
           * file[/tmp/kitchen/cache/extracted-update-center.json] action create (up to date)
           * file[/tmp/kitchen/cache/jenkins-key] action create (up to date)
           * directory[/home/jenkins] action create (up to date)
           * group[jenkins] action create (up to date)
           * user_resource_abstract_base_class[jenkins] action create[2016-09-27T13:51:49+02:00] WARN: Class Chef::Provider::User does not declare 'provides :user'.
       [2016-09-27T13:51:49+02:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.
       
             
             ================================================================================
             Error executing action `create` on resource 'user_resource_abstract_base_class[jenkins]'
             ================================================================================
             
             NotImplementedError


             -------------------
             NotImplementedError
             
             Cookbook Trace:
             ---------------
             /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:60:in `action_create'
             
             Compiled Resource:
             ------------------
             # Declared in 
             
             user_resource_abstract_base_class("jenkins") do
        action [:create]
        supports {:manage_home=>false, :non_unique=>false}
        retries 0
        retry_delay 2
        default_guard_interpreter :default
        username "jenkins"
        comment "Jenkins slave user - Created by Chef"
        gid 11119
        home "/home/jenkins"
        iterations 27855
             end
             
             Platform:
             ---------
             x86_64-linux
             
           
           ================================================================================
           Error executing action `create` on resource 'jenkins_jnlp_slave[192.168.211.147]'
           ================================================================================
           
           NotImplementedError
           -------------------
           user_resource_abstract_base_class[jenkins] (dynamically defined) had an error: NotImplementedError: NotImplementedError
           
           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:60:in `action_create'
           
           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb
           
            75: jenkins_jnlp_slave ipaddress do
            76:   remote_fs '/home/jenkins'
            77:   action [:create, :connect]
            78:   not_if { master == 'localhost' }
            79: end
           
           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb:75:in `from_file'
           
           jenkins_jnlp_slave("192.168.211.147") do
             action [:create, :connect]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_jnlp_slave
             cookbook_name "mnet_jenkins"
             recipe_name "slave"
             remote_fs "/home/jenkins"
             slave_name "192.168.211.147"
             description "Jenkins slave 192.168.211.147"
             usage_mode "normal"
             group "jenkins"
             user "jenkins"
             not_if { #code block }
           end
           
           Platform:
           ---------
           x86_64-linux
           
       
       Running handlers:
       [2016-09-27T13:51:49+02:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-09-27T13:51:49+02:00] ERROR: Exception handlers complete
       Chef Client failed. 7 resources updated in 12 seconds
       [2016-09-27T13:51:49+02:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-09-27T13:51:49+02:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-09-27T13:51:49+02:00] ERROR: jenkins_jnlp_slave[192.168.211.147] (mnet_jenkins::slave line 75) had an error: NotImplementedError: user_resource_abstract_base_class[jenkins] (dynamically defined) had an error: NotImplementedError: NotImplementedError
       [2016-09-27T13:51:49+02:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Converge failed on instance <jenkins-slave-centos07>.  Please see .kitchen/logs/jenkins-slave-centos07.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
[jenkins-slave.txt](https://github.com/chef-cookbooks/jenkins/files/495408/jenkins-slave.txt)

**Comment by jmaass** [comment]
I forgot: the same recipe used to work with chef-clients of previous versions.

**Comment by iennae** [comment]
@jmaass Do you have the same issue with the 3.0 version of this cookbook?

**Comment by docwhat** [comment]
@iennae: I have the same issue with 3.0 cookbook as well with chef-client 12.14.89

**Comment by docwhat** [comment]
So [this is the change](https://github.com/chef/chef/commit/f769d7eba17b3f5aa9e0561126bd9f6801c1bac2) in Chef that broke this using `Chef::Resource::User.new(...)`

The fix seems to be to replace `Chef::Resource::User.new(...)` with `Chef::Resource.resource_for_node(:user, node).new(...)`

**Comment by lamont-granquist** [comment]
you want to use `declare_resource(:user, "....") do ... end` similar to:  https://github.com/chef/chef/blob/63624a13e6fcbe313eb956eceab5d406bea5edfb/lib/chef/provider/apt_update.rb#L75-L78

that API goes back very far into chef 11, longer than any community cookbook support that we have.

i also don't think you needed the guard around resource_for_node, or else that's the wrong API to be using, there's a backcompatable API hanging off Chef::Resource for constructing resources that is 11.x/12.x compatible.

**Comment by jmaass** [comment]
Hi Jennifer,

when using V3.1.0 of the cookbook with the latest chef-client, I get the following error:

          ================================================================================
           Error executing action `create` on resource 'jenkins_jnlp_slave[192.168.211.187]'
           ================================================================================

           RuntimeError
           ------------
           implicit argument passing of super from method defined by define_method() is not supported. Specify all arguments explicitly.

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:55:in `block in <class:JenkinsJnlpSlave>'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb

            70: jenkins_jnlp_slave ipaddress do
            71:   remote_fs '/home/jenkins'
            72:   action [:create, :connect]
            73:   not_if { master == 'localhost' }
            74: end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/mnet_jenkins/recipes/slave.rb:70:in `from_file'

           jenkins_jnlp_slave("192.168.211.187") do
             action [:create, :connect]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :jenkins_jnlp_slave
             cookbook_name "mnet_jenkins"
             recipe_name "slave"
             remote_fs "/home/jenkins"
             slave_name "192.168.211.187"
             not_if { #code block }
           end

           Platform:
           ---------
           x86_64-linux


Mit freundlichen Grüßen/Kind regards

Jörg Maaß
Hays AG
Release Management Retail im Bereich IT
--
M-net Telekommunikations GmbH
Emmy-Noether-Str. 2 | 80992 München

Tel. 089 45200 8356 | Fax 089 45200 708356 | Mobil 0178 5352364
www.m-net.de<http://www.m-net.de/> | joerg.maass.ext@m-net.de<mailto:joerg.maass.ext@m-net.de>
M-net auf Facebook<http://www.facebook.com/Mnet.MeinNetz> | YouTube<http://www.youtube.com/user/MnetMeinNetz> | XING<http://www.xing.com/company/m-net>
Sitz München – Amtsgericht München HRB 108514
Geschäftsführer: Jens Prautzsch (Vorsitzender) | Simone Büber-Monath | Michael Fränkle
Vorsitzende des Aufsichtsrats: Erna-Maria Trixl
[M-net_Testsieger]

Von: Jennifer Davis [mailto:notifications@github.com]
Gesendet: Dienstag, 4. Oktober 2016 12:00
An: chef-cookbooks/jenkins
Cc: Maaß.Jörg; Mention
Betreff: Re: [chef-cookbooks/jenkins] user_resource_abstract_base_class[jenkins] fails with NotImplementedError (#513)


@jmaass<https://github.com/jmaass> Do you have the same issue with the 3.0 version of this cookbook?

**Comment by lamont-granquist** [comment]
@jmaass please open a new bug report and include the stacktrace.out

**Comment by jmaass** [comment]
Done, see [https://github.com/chef-cookbooks/jenkins/issues/524](https://github.com/chef-cookbooks/jenkins/issues/524).

**Comment by iennae** [comment]
This is in progress, but found some interlinking issues that are delaying this release. Going to move this particular issue off this release (and releasing what's current on master to hopefully rectify PR #524.

**Comment by iennae** [comment]
Hey folks,

Cookbook version 4.0.1 of this cookbook will resolve the specific error that is reported in this issue. There are other issues that we have discovered through testing based on the version of Jenkins used and authentication models. Please reopen this specific issue if you are still having the error message as reported above:

           user_resource_abstract_base_class[jenkins] (dynamically defined) had an error: NotImplementedError: NotImplementedError

Thanks!

**Comment by docwhat** [comment]
Still having this error with:

* Chef `12.15.19`
* compat_resource `12.16.1`
* jenkins `3.1.1`

```
[2016-10-28T15:50:31-04:00] INFO: Processing user_resource_abstract_base_class[jenkins] action create (dynamically defined)
[2016-10-28T15:50:31-04:00] WARN: Class Chef::Provider::User does not declare 'provides :user'.
[2016-10-28T15:50:31-04:00] WARN: This will no longer work in Chef 13: you must use 'provides' to use the resource's DSL.

================================================================================
Error executing action `create` on resource 'user_resource_abstract_base_class[jenkins]'
================================================================================

NotImplementedError
-------------------
NotImplementedError

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:61:in `block in <class:JenkinsJnlpSlave>'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

Compiled Resource:
------------------
# Declared in

user_resource_abstract_base_class("jenkins") do
  action [:create]
  supports {:manage_home=>false, :non_unique=>false}
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  username "jenkins"
  comment "Jenkins slave user - Created by Chef"
  gid 1000
  home "/a"
  system true
  iterations 27855
end


Platform:
---------
x86_64-linux


================================================================================
Error executing action `create` on resource 'jenkins_jnlp_slave[pickle02]'
================================================================================

NotImplementedError
-------------------
user_resource_abstract_base_class[jenkins] (dynamically defined) had an error: NotImplementedError: NotImplementedError

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/jenkins/libraries/slave_jnlp.rb:61:in `block in <class:JenkinsJnlpSlave>'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
/var/chef/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

Resource Declaration:
---------------------
# In /var/chef/cache/cookbooks/jenkins_slave/recipes/jnlp.rb

 48:           jenkins_jnlp_slave node.name
 49:         end

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/jenkins_slave/recipes/jnlp.rb:48:in `from_file'

jenkins_jnlp_slave("pickle02") do
  action [:create, :connect]
  retries 0
  retry_delay 2
  default_guard_interpreter :default
  declared_type :jenkins_jnlp_slave
  cookbook_name "jenkins_slave"
  recipe_name "jnlp"
  user "jenkins"
  group "jenkins"
  remote_fs "/a"
  labels ["docker pickle", "linux", "x86_64", "redhat", "rhel", "redhat_7.2", "rhel_7.2", "redhat_7", "rhel_7"]
  executors 4
  usage_mode "normal"
  environment {"PATH"=>"/usr/local/bin:/bin", "DOCKER_HOST"=>"tcp://127.0.0.1:2375", "DOCKER_GID"=>"993"}
  slave_name "pickle02"
  description "Jenkins slave pickle02"
end

Platform:
---------
x86_64-linux
```
